field: 75795f43-37c1-449c-846e-09a6ce0fb307 # artblock
fieldLayouts:
  0bd01d14-768d-4e29-a8d2-b99a0053004c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a78535fc-0ae8-4529-81c5-6eee8cff91c4 # image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15ee53e9-bb6b-47e0-bcae-ae791083dc7b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 259fa019-0196-438b-b5a4-24d63a2a52dd # img title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2111d658-5fbf-400a-b912-8d08b2106b99
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2815fed3-aa5c-41aa-b0d5-b7cf96cf3ab8 # subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05262eab-a316-4bbf-b958-2dc0956e7bf7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8e40d779-6123-468f-ae1a-aeb7f707f89f
        userCondition: null
fields:
  259fa019-0196-438b-b5a4-24d63a2a52dd: # img title
    columnSuffix: nbelocdp
    contentColumnType: text
    fieldGroup: null
    handle: imgTitle
    instructions: null
    name: 'img title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2815fed3-aa5c-41aa-b0d5-b7cf96cf3ab8: # subtitle
    columnSuffix: omfkrtai
    contentColumnType: text
    fieldGroup: null
    handle: subtitle
    instructions: null
    name: subtitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a78535fc-0ae8-4529-81c5-6eee8cff91c4: # image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:6644975d-24b9-4f9b-a626-6af14af0c658' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:6644975d-24b9-4f9b-a626-6af14af0c658' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:6644975d-24b9-4f9b-a626-6af14af0c658' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: image
sortOrder: 1
