field: 75795f43-37c1-449c-846e-09a6ce0fb307 # artblock
fieldLayouts:
  dc2fa0ac-9545-4644-8b32-29631ec400eb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: efd07511-1da3-483d-b51d-c9c47a789894 # img title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89b7bd79-9b52-43b1-9508-0fb01f1706f0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2cfb7206-42db-402b-8bbb-22664f204ee2
        userCondition: null
fields:
  efd07511-1da3-483d-b51d-c9c47a789894: # img title
    columnSuffix: kziqldoi
    contentColumnType: text
    fieldGroup: null
    handle: imgTitle
    instructions: null
    name: 'img title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: imgTitle
name: 'img title'
sortOrder: 2
