field: 1e2f2daf-cb1c-4f11-ab96-4d7284a77689 # subtitle
fieldLayouts:
  2db493cb-93e4-4567-beb0-eb2526ac9719:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: efebddb6-b5cb-4ea8-a7c7-79dcf097e588 # subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ce2ed1d-4689-4834-a8bf-83452b6988bb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1911b052-8280-48ff-b66a-a5345a1de903
        userCondition: null
fields:
  efebddb6-b5cb-4ea8-a7c7-79dcf097e588: # subtitle
    columnSuffix: shwrxucm
    contentColumnType: text
    fieldGroup: null
    handle: subtitle
    instructions: null
    name: subtitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: subtitle
name: subtitle
sortOrder: 1
