columnSuffix: null
contentColumnType: string
fieldGroup: 5aaf74f2-2e29-43ef-9b34-619d2bfebd43 # Common
handle: artblock
instructions: null
name: artblock
searchable: false
settings:
  contentTable: '{{%matrixcontent_artblock}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
