defaultPlacement: end
enableVersioning: true
handle: contentblock
name: Contentblock
propagationMethod: all
siteSettings:
  10b52a70-48ac-46b7-bb76-2cb293f44b7b: # Template for an artist
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
